#!/bin/bash

##################################################################################
#                                                                                #
#    Calculates the mean radius cutoff from the xy_rdf data generated for across #
#    the systems, temperatures and replicas hardcoded in the script.             #
#                                                                                #
#    This is a script that's being called from `run.sh`.                         #
#                                                                                #
#    It removes any data and reports generated by previous runs of this          #
#    protocol.                                                                   #
#                                                                                #
#    The `lipidList.dat` is taken as input - This is hardcoded as of now: A file #
#    consisting of all the information about (lipids) segID that to be included  #
#    in the analysis protocol.                                                   #
#                                                                                #
#    A python script `rCutoffFromReplica.py` is called from the script which     #
#    calculates the mean r cutoff.                                               #
#                                                                                #
#    The output is forwarded to the file `avgRcutoff.dat` which is stored in the #
#    corresponding working directory.                                            #
#                                                                                #
##################################################################################

CURRENT=$PWD

for SYSTEM in DAPC DIPC POPC
do
    rm -rf ${CURRENT}/${SYSTEM}/*/avgRcutoff.dat
    rm -rf ${CURRENT}/${SYSTEM}/*/avgRcutoff.report
    lipidList=${CURRENT}/${SYSTEM}/lipidList.dat

    for i in 298K 313K 323K 333K 343K 353K 373K 423K 450K
    do
        if [ -d "${CURRENT}/${SYSTEM}/${i}" ]
        then
                cd ${SYSTEM}/${i}/

                echo "Calculating avg xy-RDF for ${SYSTEM}  at Temperature ${i}"

                while read lipid
                do

                    echo "python3 rCutoffFromReplica.py --dat_files *${SYSTEM}*${lipid}-${lipid}.xyRDF" $lipidList >> avgRcutoff.report

                    rCutoff=$(python3 ${CURRENT}/rCutoffFromReplica.py --dat_files */*${SYSTEM}*${lipid}-${lipid}.xyRDF)

                    echo ${lipid} ${rCutoff} >> avgRcutoff.dat

                done<$lipidList

                cd ${CURRENT}
        fi
    done
done
